// React UI components
export { StatusBar } from './StatusBar'
export { BPMSlider } from './BPMSlider'
export { PromptInput } from './PromptInput'
export { PlayButton } from './PlayButton'
export { Visualizer } from './Visualizer'
export { QuickActions } from './QuickActions'
export { EmptyState } from './EmptyState'
export { ErrorDisplay } from './ErrorDisplay'
export { HistoryControls } from './HistoryControls'
export { SnapshotPanel, SnapshotButton } from './SnapshotPanel'
export { PromptHistory } from './PromptHistory'
export type { PromptHistoryItem, PromptStatus } from './PromptHistory'
export { QueuedChanges, QueuedIndicator } from './QueuedChanges'
export { LayerControl, LayerControlPanel } from './LayerControl'
export type { LayerControlProps, LayerControlPanelProps } from './LayerControl'

// Phase 6: Performance UI components
export { BeatIndicator, CompactBeatIndicator } from './BeatIndicator'
export type { BeatIndicatorProps } from './BeatIndicator'
export { EnergyMeter, CompactEnergyMeter } from './EnergyMeter'
export type { EnergyMeterProps } from './EnergyMeter'
export { SectionIndicator, SectionSelector } from './SectionIndicator'
export type { SectionIndicatorProps, SectionType } from './SectionIndicator'
export { ArrangementActions, ExtendedArrangementActions, DropButton } from './ArrangementActions'
export type { ArrangementActionsProps, ArrangementAction } from './ArrangementActions'
export { EmergencyStop, FixedEmergencyStop, CompactStopButton } from './EmergencyStop'
export type { EmergencyStopProps } from './EmergencyStop'
export { PresetButtons, CompactPresetBar } from './PresetButtons'
export type { PresetButtonsProps, Preset } from './PresetButtons'
export { MobileLayout, useMobileLayout } from './MobileLayout'
export type { MobileLayoutProps } from './MobileLayout'
export { VibePicker, VibeIndicator, VibeBar } from './VibePicker'
export type { VibePickerProps } from './VibePicker'
export { VoiceInput, VoiceButton, useVoiceInputSupport } from './VoiceInput'
export type { VoiceInputProps } from './VoiceInput'

// Re-export visualizers
export * from './visualizers'
